networks:
  inter-network:
    driver: bridge

services:
  backend-java:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8089:8080"
    networks:
      - inter-network
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: "docker"
      server.front: ${FRONTEND_URL}
      oauth2.gh-id: ${GH_CLIENT_ID}
      oauth2.gh-secret: ${GH_CLIENT_SECRET}
      oauth2.google-id: ${GOOGLE_CLIENT_ID}
      oauth2.google-secret: ${GOOGLE_CLIENT_SECRET}

  frontend-vite:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      API_URL: "http://localhost:8089"
    depends_on:
      - backend-java
    ports: 
      - 3000:5173
    networks:
      - inter-network
