version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8089:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on: [backend]
