name: Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build backend image
      run: docker build ./backend --file ./backend/Dockerfile
    - name: Build frontend image
      run: docker build ./frontend --file ./frontend/Dockerfile
